initial-service-host: "hetzner-catalog"
d2c-service-config:
  type: "docker"
  image: "ghcr.io/rollun-lc/weave-metrics-proxy/weave-metrics-proxy/image"
  version: "latest"
  name: "catalog-wnp"
  description: "A weave net metrics proxy. Serves metrics from weave net to prometheus."
  project: "Monitoring:VM"
  ports:
    - value: 80
      protocol: "TCP"
  env:
    - name: "PORT"
      value: "80"
    - name: "METRICS_FILE"
      value: "/tmp/weave-metrics/metrics.txt"
  volumes:
    - dst: /tmp/weave-metrics
      src: /ebs/containers/catalog-wnp/weave-metrics
